name: wav
description: A package for creating waveform audio.
version: 1.0.0
repository: https://github.com/tytydraco/template

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: any
